---
title: "Publicaciones"
---

#### Publicaciones

**Estrada Álvarez, J.M.**, Ossa García, X., del Quijano del Gordo, C.I. et al. **Validation of the chronic respiratory questionnaire in the Colombian population with chronic obstructive pulmonary disease**. Qual Life Res 24, 2039–2044 (2015). <https://doi.org/10.1007/s11136-015-0939-1>

**Estrada Álvarez JM**, Ospina Ramírez JJ, Hincapié Acuña M, Gómez González MP. **Estimación del intervalo serial y número reproductivo básico para los casos importados de COVID-19**. Rev salud pública [Internet]. 2020 Mar-Abr [citado 12 Ago 2021];22(2). Disponible en: <http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S0124-00642020000200214&lng=en&nrm=iso>

**Estrada-Álvarez Jorge Mario**, Orozco-Hernández Juan Pablo, Aristizábal-Franco Luis Evelio. **Validación del puntaje de valoración de la gravedad de la enfermedad pulmonar obstructiva crónica en población colombiana en un servicio de atención primaria.** Biomed.  [Internet]. 2020  Dec [cited  2022  Sep  01] ;  40( 4 ): 664-672. <https://doi.org/10.7705/biomedica.5123.>

Cardona N, Ocampo SJ, **Estrada JM**, Mojica MI, Porras GL. **Caracterización clínica y funcional de pacientes con atrofia muscular espinal en el centro-occidente colombiano**. biomedica [Internet]. 1 de mayo de 2022 [citado 1 de septiembre de 2022];42(Sp. 1):89. <https://revistabiomedica.org/index.php/biomedica/article/view/6178>

Osuna-Julio DL, **Estrada-Álvarez JM**, Araya-Marín MC, Meléndez-Puchana LA, Pérez-Rendón AL. **Calidad de vida relacionada a la salud en pacientes con enfermedad pulmonar obstructiva crónica en Pereira, Colombia**. Rev Ter [Internet]. 2021;15(2):56-62. <https://138.59.135.20/index.php/RT/article/view/139>


